package server;

/**
 * Enum identifying each CommMessage and their implicit type.
 * 
 * @author halvor //TODO
 *
 */
public enum CommEnum {
	
	//LOGIN REQUEST CLIENT->SERVER
	LOGIN,
	
	//LOGIN REPLY SERVER->CLIENT
	// -- OK
	LOGINSUCCESSFUL,
	// -- NOT OK
	LOGINFAILED,
	
	//SERVER->CLIENT ERROR MESSAGE: NOT LOGGED IN
	NOTLOGGEDIN,
	
	//SERVER->CLIENT GENERAL SUCCESS MESSAGE
	SUCCESS,
	
	//CLIENT-SERVER ADD AN EVENT
	ADDEVENT,
	
	//CLIENT->SERVER REMOVE AN EVENT
	REMOVEEVENT, 
	
	//CLIENT->SERVER GET EVENT LIST
	GETEVENTS,
	
	//CLIENT->SERVER UPDATE ENTIRE PARTICIPANTLIST
	UPDATEPARTICIPANTLIST, 
	
	//CLIENT->SERVER ADD SINGLE PARTICIPANT TO EVENT
	ADDPARTICIPANT, 
	
	//CLIENT->SERVER REMOVE SINGLE PARTICIPANT FROM EVENT
	REMOVEPARTICIPANT, 
	
	//CLIENT->SERVER UPDATE CONTACT INFORMATION
	UPDATECONTACTINFORMATION,
        
    //CLIENT->SERVER REGISTER NEW USER
    REGISTERNEWUSER,
	
	// SERVER -> CLIENT UPDATED MESSAGES
	NEWMESSAGES,
	
	// SERVER-> CLIENT ALARM notification
	NEWALARM,
	
	// SERVER-> CLIENT User already in database
	USERNAMEALREADYTAKEN,
	
	//SERVER-> CLIENT Email address already in database (The email address
	// for the registered user)
	EMAILADDRESSALREADYTAKEN

}
